// Code generated by protoc-gen-go. DO NOT EDIT.
// source: attribution/proto/impression/impression.proto

package impression

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdType int32

const (
	IdType_invalid                   IdType = 0
	IdType_encrypted_hash_imei       IdType = 1
	IdType_encrypted_hash_idfa       IdType = 2
	IdType_encrypted_hash_oaid       IdType = 3
	IdType_encrypted_hash_android_id IdType = 4
)

var IdType_name = map[int32]string{
	0: "invalid",
	1: "encrypted_hash_imei",
	2: "encrypted_hash_idfa",
	3: "encrypted_hash_oaid",
	4: "encrypted_hash_android_id",
}

var IdType_value = map[string]int32{
	"invalid":                   0,
	"encrypted_hash_imei":       1,
	"encrypted_hash_idfa":       2,
	"encrypted_hash_oaid":       3,
	"encrypted_hash_android_id": 4,
}

func (x IdType) String() string {
	return proto.EnumName(IdType_name, int32(x))
}

func (IdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e7d605016d515df, []int{0}
}

type Request struct {
	CampaignId           string    `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Records              []*Record `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7d605016d515df, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *Request) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Response struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7d605016d515df, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Record struct {
	IdType               IdType   `protobuf:"varint,1,opt,name=id_type,json=idType,proto3,enum=impression.IdType" json:"id_type,omitempty"`
	IdValue              string   `protobuf:"bytes,2,opt,name=id_value,json=idValue,proto3" json:"id_value,omitempty"`
	ImpressionTime       uint64   `protobuf:"varint,3,opt,name=impression_time,json=impressionTime,proto3" json:"impression_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7d605016d515df, []int{2}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetIdType() IdType {
	if m != nil {
		return m.IdType
	}
	return IdType_invalid
}

func (m *Record) GetIdValue() string {
	if m != nil {
		return m.IdValue
	}
	return ""
}

func (m *Record) GetImpressionTime() uint64 {
	if m != nil {
		return m.ImpressionTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("impression.IdType", IdType_name, IdType_value)
	proto.RegisterType((*Request)(nil), "impression.Request")
	proto.RegisterType((*Response)(nil), "impression.Response")
	proto.RegisterType((*Record)(nil), "impression.Record")
}

func init() {
	proto.RegisterFile("attribution/proto/impression/impression.proto", fileDescriptor_5e7d605016d515df)
}

var fileDescriptor_5e7d605016d515df = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6b, 0xab, 0x40,
	0x10, 0xc7, 0x9f, 0x49, 0xd0, 0xbc, 0x09, 0xe4, 0xc9, 0xbe, 0xc3, 0x33, 0x87, 0x47, 0x43, 0x2e,
	0x95, 0xfe, 0x50, 0x68, 0x2f, 0xbd, 0xf4, 0xd0, 0xde, 0x72, 0x95, 0x50, 0x4a, 0x2f, 0xb2, 0x71,
	0xa6, 0xc9, 0x40, 0xdc, 0xb5, 0xee, 0x1a, 0xf0, 0xd4, 0x7f, 0xbd, 0x44, 0x09, 0xda, 0x12, 0xda,
	0x93, 0xee, 0xe7, 0xbb, 0x9f, 0x61, 0x96, 0x19, 0xb8, 0x96, 0xd6, 0x96, 0xbc, 0xae, 0x2c, 0x6b,
	0x15, 0x17, 0xa5, 0xb6, 0x3a, 0xe6, 0xbc, 0x28, 0xc9, 0x98, 0x03, 0xe8, 0x7e, 0xa3, 0x26, 0x13,
	0xd0, 0x91, 0xc5, 0x33, 0x78, 0x09, 0xbd, 0x55, 0x64, 0xac, 0x38, 0x83, 0x49, 0x26, 0xf3, 0x42,
	0xf2, 0x46, 0xa5, 0x8c, 0x81, 0x33, 0x77, 0xc2, 0xdf, 0x09, 0x1c, 0xd1, 0x12, 0xc5, 0x15, 0x78,
	0x25, 0x65, 0xba, 0x44, 0x13, 0x0c, 0xe6, 0xc3, 0x70, 0x72, 0x23, 0xa2, 0x5e, 0xed, 0xa4, 0x89,
	0x92, 0xe3, 0x95, 0xc5, 0x1d, 0x8c, 0x13, 0x32, 0x85, 0x56, 0x86, 0xfa, 0xa6, 0xf3, 0xb3, 0x59,
	0x83, 0xdb, 0x22, 0x71, 0x09, 0x1e, 0x63, 0x6a, 0xeb, 0x82, 0x9a, 0x76, 0xa6, 0x9f, 0xbd, 0x25,
	0xae, 0xea, 0x82, 0x12, 0x97, 0x9b, 0xaf, 0x98, 0xc1, 0x98, 0x31, 0xdd, 0xcb, 0x5d, 0x45, 0xc1,
	0xa0, 0x69, 0xde, 0x63, 0x7c, 0x3a, 0x1c, 0xc5, 0x39, 0xfc, 0xe9, 0xbc, 0xd4, 0x72, 0x4e, 0xc1,
	0x70, 0xee, 0x84, 0xa3, 0x64, 0xda, 0xe1, 0x15, 0xe7, 0x74, 0xf1, 0x0e, 0x6e, 0x5b, 0x55, 0x4c,
	0xc0, 0x63, 0xb5, 0x97, 0x3b, 0x46, 0xff, 0x97, 0xf8, 0x07, 0x7f, 0x49, 0x65, 0x65, 0x5d, 0x58,
	0xc2, 0x74, 0x2b, 0xcd, 0x36, 0xe5, 0x9c, 0xd8, 0x77, 0x4e, 0x05, 0xf8, 0x2a, 0xfd, 0xc1, 0x89,
	0x40, 0x4b, 0x46, 0x7f, 0x28, 0xfe, 0xc3, 0xec, 0x4b, 0x20, 0x15, 0x96, 0x9a, 0x31, 0x65, 0xf4,
	0x47, 0x8f, 0x0c, 0x61, 0xa6, 0xf3, 0xc8, 0x92, 0xca, 0x48, 0xd9, 0xa8, 0x37, 0xd8, 0x76, 0x78,
	0xbd, 0xf7, 0xbf, 0xdc, 0x6f, 0xd8, 0x6e, 0xab, 0x75, 0x94, 0xe9, 0x3c, 0x5e, 0xb5, 0xc2, 0x03,
	0xc6, 0xfd, 0x5d, 0xf8, 0x6e, 0x2f, 0xd6, 0x6e, 0x43, 0x6e, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xa7, 0x08, 0x0c, 0x66, 0x3e, 0x02, 0x00, 0x00,
}
