// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/TencentAd/attribution/attribution/proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 用户id类型
type IdType int32

const (
	IdType_RetrievalId     IdType = 0
	IdType_Device          IdType = 1
	IdType_QQOpenId        IdType = 2
	IdType_Wuid            IdType = 3
	IdType_Mac             IdType = 4
	IdType_AndroidId       IdType = 5
	IdType_Qadid           IdType = 6
	IdType_MappedAndroidId IdType = 7
	IdType_MappedMac       IdType = 8
	IdType_Taid            IdType = 9
	IdType_Oaid            IdType = 10
	IdType_HashOaid        IdType = 11
	IdType_Uuid            IdType = 12
)

var IdType_name = map[int32]string{
	0:  "RetrievalId",
	1:  "Device",
	2:  "QQOpenId",
	3:  "Wuid",
	4:  "Mac",
	5:  "AndroidId",
	6:  "Qadid",
	7:  "MappedAndroidId",
	8:  "MappedMac",
	9:  "Taid",
	10: "Oaid",
	11: "HashOaid",
	12: "Uuid",
}

var IdType_value = map[string]int32{
	"RetrievalId":     0,
	"Device":          1,
	"QQOpenId":        2,
	"Wuid":            3,
	"Mac":             4,
	"AndroidId":       5,
	"Qadid":           6,
	"MappedAndroidId": 7,
	"MappedMac":       8,
	"Taid":            9,
	"Oaid":            10,
	"HashOaid":        11,
	"Uuid":            12,
}

func (x IdType) String() string {
	return proto.EnumName(IdType_name, int32(x))
}

func (IdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ce649f320108c4b, []int{0}
}

// 用户信息，主要包含支持的id体系
type UserData struct {
	Imei                 string   `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	Idfa                 string   `protobuf:"bytes,2,opt,name=idfa,proto3" json:"idfa,omitempty"`
	QqOpenid             string   `protobuf:"bytes,3,opt,name=qq_openid,json=qqOpenid,proto3" json:"qq_openid,omitempty"`
	Wuid                 string   `protobuf:"bytes,4,opt,name=wuid,proto3" json:"wuid,omitempty"`
	Mac                  string   `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
	AndroidId            string   `protobuf:"bytes,6,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	Qadid                string   `protobuf:"bytes,7,opt,name=qadid,proto3" json:"qadid,omitempty"`
	MappedAndroidId      []string `protobuf:"bytes,8,rep,name=mapped_android_id,json=mappedAndroidId,proto3" json:"mapped_android_id,omitempty"`
	MappedMac            []string `protobuf:"bytes,9,rep,name=mapped_mac,json=mappedMac,proto3" json:"mapped_mac,omitempty"`
	Taid                 string   `protobuf:"bytes,10,opt,name=taid,proto3" json:"taid,omitempty"`
	Oaid                 string   `protobuf:"bytes,11,opt,name=oaid,proto3" json:"oaid,omitempty"`
	HashOaid             string   `protobuf:"bytes,12,opt,name=hash_oaid,json=hashOaid,proto3" json:"hash_oaid,omitempty"`
	Uuid                 string   `protobuf:"bytes,13,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Ip                   string   `protobuf:"bytes,14,opt,name=ip,proto3" json:"ip,omitempty"`
	Ipv6                 string   `protobuf:"bytes,15,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ce649f320108c4b, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *UserData) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *UserData) GetQqOpenid() string {
	if m != nil {
		return m.QqOpenid
	}
	return ""
}

func (m *UserData) GetWuid() string {
	if m != nil {
		return m.Wuid
	}
	return ""
}

func (m *UserData) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *UserData) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *UserData) GetQadid() string {
	if m != nil {
		return m.Qadid
	}
	return ""
}

func (m *UserData) GetMappedAndroidId() []string {
	if m != nil {
		return m.MappedAndroidId
	}
	return nil
}

func (m *UserData) GetMappedMac() []string {
	if m != nil {
		return m.MappedMac
	}
	return nil
}

func (m *UserData) GetTaid() string {
	if m != nil {
		return m.Taid
	}
	return ""
}

func (m *UserData) GetOaid() string {
	if m != nil {
		return m.Oaid
	}
	return ""
}

func (m *UserData) GetHashOaid() string {
	if m != nil {
		return m.HashOaid
	}
	return ""
}

func (m *UserData) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UserData) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *UserData) GetIpv6() string {
	if m != nil {
		return m.Ipv6
	}
	return ""
}

func init() {
	proto.RegisterEnum("user.IdType", IdType_name, IdType_value)
	proto.RegisterType((*UserData)(nil), "user.UserData")
}

func init() { proto.RegisterFile("github.com/TencentAd/attribution/attribution/proto/user/user.proto", fileDescriptor_4ce649f320108c4b) }

var fileDescriptor_4ce649f320108c4b = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xc1, 0x6a, 0xdc, 0x30,
	0x10, 0x86, 0xbb, 0xb6, 0xd7, 0x6b, 0xcd, 0x6e, 0xb2, 0xea, 0xb4, 0x07, 0x41, 0x09, 0xa4, 0xa1,
	0x87, 0x90, 0xc3, 0xe6, 0x50, 0xc8, 0xbd, 0x25, 0x87, 0xee, 0x61, 0x09, 0xbb, 0x24, 0xf4, 0x68,
	0x14, 0x8f, 0x42, 0x04, 0xb5, 0x2d, 0x7b, 0x65, 0x97, 0xbe, 0x55, 0x9f, 0xad, 0x4f, 0x50, 0x46,
	0x72, 0x43, 0x7a, 0x31, 0xbf, 0xbe, 0xd1, 0x78, 0xf4, 0xff, 0x0c, 0x7c, 0xd4, 0xde, 0xf7, 0xf6,
	0x71, 0xf0, 0xb6, 0x6d, 0xae, 0x5d, 0xdf, 0xfa, 0xf6, 0x7a, 0x38, 0x9a, 0x3e, 0x7c, 0x36, 0xe1,
	0x8c, 0x19, 0xeb, 0x8b, 0x3f, 0x09, 0x14, 0x0f, 0x47, 0xd3, 0xdf, 0x6a, 0xaf, 0x11, 0x21, 0xb3,
	0xb5, 0xb1, 0x6a, 0x76, 0x3e, 0xbb, 0x14, 0x87, 0xa0, 0x03, 0xa3, 0x27, 0xad, 0x92, 0x89, 0xd1,
	0x93, 0xc6, 0x0f, 0x20, 0xba, 0xae, 0x6c, 0x9d, 0x69, 0x2c, 0xa9, 0x34, 0x14, 0x8a, 0xae, 0xbb,
	0x0b, 0x67, 0x6e, 0xf8, 0x39, 0x58, 0x52, 0x59, 0x6c, 0x60, 0x8d, 0x12, 0xd2, 0x5a, 0x57, 0x6a,
	0x1e, 0x10, 0x4b, 0x3c, 0x03, 0xd0, 0x0d, 0xf5, 0xad, 0xa5, 0xd2, 0x92, 0xca, 0x43, 0x41, 0x4c,
	0x64, 0x4b, 0xf8, 0x1e, 0xe6, 0x9d, 0x26, 0x4b, 0x6a, 0x11, 0x2a, 0xf1, 0x80, 0x57, 0xf0, 0xb6,
	0xd6, 0xce, 0x19, 0x2a, 0x5f, 0xf5, 0x16, 0xe7, 0xe9, 0xa5, 0x38, 0xac, 0x63, 0xe1, 0xcb, 0xcb,
	0x1f, 0xce, 0x00, 0xa6, 0xbb, 0x3c, 0x59, 0x84, 0x4b, 0x22, 0x92, 0x9d, 0xae, 0xf8, 0x95, 0x5e,
	0x5b, 0x52, 0x10, 0x5f, 0xc9, 0x9a, 0x59, 0xcb, 0x6c, 0x19, 0x19, 0x6b, 0xb6, 0xfa, 0xac, 0x8f,
	0xcf, 0x65, 0x28, 0xac, 0xa2, 0x55, 0x06, 0x77, 0x53, 0xc3, 0xc0, 0x56, 0x4f, 0x62, 0x03, 0x6b,
	0x3c, 0x85, 0xc4, 0x3a, 0x75, 0x1a, 0x48, 0x62, 0x5d, 0xc8, 0xcf, 0x8d, 0x37, 0x6a, 0x3d, 0xe5,
	0xe7, 0xc6, 0x9b, 0xab, 0xdf, 0x33, 0xc8, 0xb7, 0x74, 0xff, 0xcb, 0x19, 0x5c, 0xc3, 0xf2, 0x60,
	0x7c, 0x6f, 0xcd, 0xa8, 0x7f, 0x6c, 0x49, 0xbe, 0x41, 0x80, 0xfc, 0xd6, 0x8c, 0xb6, 0x32, 0x72,
	0x86, 0x2b, 0x28, 0xf6, 0x7b, 0x8e, 0x75, 0x4b, 0x32, 0xc1, 0x02, 0xb2, 0xef, 0x83, 0x25, 0x99,
	0xe2, 0x02, 0xd2, 0x9d, 0xae, 0x64, 0x86, 0x27, 0x20, 0x5e, 0x1c, 0xcb, 0x39, 0x0a, 0x98, 0xef,
	0x39, 0x28, 0x99, 0xe3, 0x3b, 0x58, 0xef, 0xfe, 0x4f, 0x44, 0x2e, 0xf8, 0xfa, 0xee, 0x5f, 0x02,
	0xb2, 0xe0, 0x1f, 0xde, 0x6b, 0x4b, 0x52, 0xb0, 0x62, 0x43, 0x12, 0x78, 0xe4, 0xb7, 0xc9, 0x9e,
	0x5c, 0x32, 0x7f, 0xe0, 0x91, 0xab, 0xaf, 0x9f, 0xe0, 0xa2, 0x6a, 0xeb, 0x8d, 0x37, 0x4d, 0x65,
	0x1a, 0xbf, 0x79, 0xb5, 0x5e, 0x71, 0x9d, 0x36, 0xbc, 0x4d, 0x8f, 0x79, 0xd0, 0x9f, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x16, 0x72, 0x54, 0x8f, 0x7f, 0x02, 0x00, 0x00,
}
