// Code generated by protoc-gen-go. DO NOT EDIT.
// source: attribution/proto/conv/conv.proto

package conv

import (
	fmt "fmt"
	click "github.com/TencentAd/attribution/attribution/proto/click"
	user "github.com/TencentAd/attribution/attribution/proto/user"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConversionLog struct {
	UserData             *user.UserData `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	EventTime            int64          `protobuf:"varint,2,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	AppId                string         `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ConvId               string         `protobuf:"bytes,4,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	CampaignId           int64          `protobuf:"varint,5,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Index                int32          `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	MatchClick           *MatchClick    `protobuf:"bytes,1000,opt,name=match_click,json=matchClick,proto3" json:"match_click,omitempty"`
	OriginalContent      string         `protobuf:"bytes,1001,opt,name=original_content,json=originalContent,proto3" json:"original_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConversionLog) Reset()         { *m = ConversionLog{} }
func (m *ConversionLog) String() string { return proto.CompactTextString(m) }
func (*ConversionLog) ProtoMessage()    {}
func (*ConversionLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_e165194b454c0299, []int{0}
}

func (m *ConversionLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversionLog.Unmarshal(m, b)
}
func (m *ConversionLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversionLog.Marshal(b, m, deterministic)
}
func (m *ConversionLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversionLog.Merge(m, src)
}
func (m *ConversionLog) XXX_Size() int {
	return xxx_messageInfo_ConversionLog.Size(m)
}
func (m *ConversionLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversionLog.DiscardUnknown(m)
}

var xxx_messageInfo_ConversionLog proto.InternalMessageInfo

func (m *ConversionLog) GetUserData() *user.UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

func (m *ConversionLog) GetEventTime() int64 {
	if m != nil {
		return m.EventTime
	}
	return 0
}

func (m *ConversionLog) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ConversionLog) GetConvId() string {
	if m != nil {
		return m.ConvId
	}
	return ""
}

func (m *ConversionLog) GetCampaignId() int64 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *ConversionLog) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ConversionLog) GetMatchClick() *MatchClick {
	if m != nil {
		return m.MatchClick
	}
	return nil
}

func (m *ConversionLog) GetOriginalContent() string {
	if m != nil {
		return m.OriginalContent
	}
	return ""
}

type MatchClick struct {
	ClickLog             *click.ClickLog `protobuf:"bytes,1,opt,name=click_log,json=clickLog,proto3" json:"click_log,omitempty"`
	MatchIdType          user.IdType     `protobuf:"varint,2,opt,name=match_id_type,json=matchIdType,proto3,enum=user.IdType" json:"match_id_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MatchClick) Reset()         { *m = MatchClick{} }
func (m *MatchClick) String() string { return proto.CompactTextString(m) }
func (*MatchClick) ProtoMessage()    {}
func (*MatchClick) Descriptor() ([]byte, []int) {
	return fileDescriptor_e165194b454c0299, []int{1}
}

func (m *MatchClick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchClick.Unmarshal(m, b)
}
func (m *MatchClick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchClick.Marshal(b, m, deterministic)
}
func (m *MatchClick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchClick.Merge(m, src)
}
func (m *MatchClick) XXX_Size() int {
	return xxx_messageInfo_MatchClick.Size(m)
}
func (m *MatchClick) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchClick.DiscardUnknown(m)
}

var xxx_messageInfo_MatchClick proto.InternalMessageInfo

func (m *MatchClick) GetClickLog() *click.ClickLog {
	if m != nil {
		return m.ClickLog
	}
	return nil
}

func (m *MatchClick) GetMatchIdType() user.IdType {
	if m != nil {
		return m.MatchIdType
	}
	return user.IdType_RetrievalId
}

func init() {
	proto.RegisterType((*ConversionLog)(nil), "conv.ConversionLog")
	proto.RegisterType((*MatchClick)(nil), "conv.MatchClick")
}

func init() { proto.RegisterFile("attribution/proto/conv/conv.proto", fileDescriptor_e165194b454c0299) }

var fileDescriptor_e165194b454c0299 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xda, 0x26, 0x6d, 0xb6, 0x5f, 0x7f, 0x64, 0x7d, 0x9f, 0xbe, 0xa8, 0x12, 0x22, 0x14,
	0x0e, 0x11, 0xa0, 0x14, 0x95, 0x37, 0xa0, 0x5c, 0x22, 0x95, 0x4b, 0x54, 0xce, 0x91, 0x6b, 0x5b,
	0xc1, 0x22, 0xb1, 0xad, 0xd4, 0xad, 0xe8, 0xeb, 0xf0, 0x74, 0xf0, 0x16, 0xc8, 0x76, 0x0b, 0x1c,
	0x7a, 0x59, 0xcd, 0xce, 0xae, 0xc6, 0xb3, 0x63, 0xb8, 0xc0, 0x5a, 0x37, 0x7c, 0xbd, 0xd5, 0x5c,
	0x8a, 0x99, 0x6a, 0xa4, 0x96, 0x33, 0x22, 0xc5, 0xce, 0x96, 0xd4, 0xf6, 0xa8, 0x63, 0xf0, 0xe4,
	0xc4, 0xe2, 0x76, 0xc3, 0x1a, 0x5b, 0xdc, 0xe2, 0xe4, 0xf2, 0x84, 0x56, 0xc5, 0xc9, 0xab, 0xab,
	0x6e, 0x69, 0xfa, 0xde, 0x82, 0xc1, 0x42, 0x8a, 0x1d, 0x6b, 0x36, 0x5c, 0x8a, 0xa5, 0x2c, 0xd1,
	0x0d, 0x84, 0x46, 0xa4, 0xa0, 0x58, 0xe3, 0xc8, 0x8b, 0xbd, 0xa4, 0x3f, 0x1f, 0xa6, 0x56, 0xf6,
	0x79, 0xc3, 0x9a, 0x47, 0xac, 0x71, 0xde, 0xdb, 0x1e, 0x10, 0x3a, 0x03, 0x60, 0x3b, 0x26, 0x74,
	0xa1, 0x79, 0xcd, 0xa2, 0x56, 0xec, 0x25, 0xed, 0x3c, 0xb4, 0xcc, 0x8a, 0xd7, 0x0c, 0xfd, 0x83,
	0x00, 0x2b, 0x55, 0x70, 0x1a, 0xb5, 0x63, 0x2f, 0x09, 0x73, 0x1f, 0x2b, 0x95, 0x51, 0xf4, 0x1f,
	0xba, 0xe6, 0x08, 0xc3, 0x77, 0x2c, 0x1f, 0x98, 0x36, 0xa3, 0xe8, 0x1c, 0xfa, 0x04, 0xd7, 0x0a,
	0xf3, 0x52, 0x98, 0xa1, 0x6f, 0xf5, 0xe0, 0x48, 0x65, 0x14, 0xfd, 0x05, 0x9f, 0x0b, 0xca, 0xde,
	0xa2, 0x20, 0xf6, 0x12, 0x3f, 0x77, 0x0d, 0x9a, 0x43, 0xbf, 0xc6, 0x9a, 0xbc, 0x14, 0xf6, 0xb2,
	0xe8, 0xa3, 0x6b, 0x5d, 0x8f, 0x53, 0x9b, 0xda, 0x93, 0x99, 0x2c, 0xcc, 0x20, 0x87, 0xfa, 0x1b,
	0xa3, 0x6b, 0x18, 0xcb, 0x86, 0x97, 0x5c, 0xe0, 0xaa, 0x20, 0x52, 0x68, 0x26, 0x74, 0xf4, 0xd9,
	0xb5, 0x6e, 0x46, 0xc7, 0xc1, 0xc2, 0xf1, 0xd3, 0x0a, 0xe0, 0x47, 0x05, 0xdd, 0x42, 0x68, 0xdf,
	0x29, 0x2a, 0x59, 0x1e, 0x02, 0x1a, 0xa5, 0x2e, 0x53, 0xbb, 0xb0, 0x94, 0x65, 0xde, 0x23, 0x07,
	0x84, 0xee, 0x60, 0xe0, 0xbc, 0x71, 0x5a, 0xe8, 0xbd, 0x72, 0x21, 0x0d, 0xe7, 0x7f, 0x5c, 0xa4,
	0x19, 0x5d, 0xed, 0x15, 0xcb, 0x9d, 0x7d, 0xd7, 0x3c, 0x5c, 0xc1, 0x94, 0xc8, 0x3a, 0xd5, 0x4c,
	0x10, 0x26, 0x74, 0xfa, 0xeb, 0x17, 0xdd, 0x9f, 0xd9, 0xb3, 0xd6, 0x81, 0xc5, 0xf7, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x5b, 0x66, 0xef, 0xf0, 0x32, 0x02, 0x00, 0x00,
}
